module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        waterIntake: {
          primary: "#2686BA",
          background: "#c8ecff",
          hover: "#349ad1",
          active: "#54b8ee",
        },
        waterIntakeDark: {
          primary: "#2686BA",
          hover: "#2a4365",
          active: "#1e3656",
          text: "#ffffff",
          border: "#4a5568",
        },
        activity: {
          primary: "#FBB24B",
          background: "#fcd49c",
          hover: "#FCBA5F",
          active: "#FCBA5F",
          text: "#dc8204",
        },
        activityDark: {
          primary: "#FBB24B",
          background: "#FA980F",
          button: "#FDD49B",
          hover: "#FBB24B",
          active: "#FCBA5F",
          text: "#FFFFFF",
          border: "#2D2F33",
        },
        pressure: {
          primary: "#FF5CB6",
          background: "#FFADDC",
          hover: "#FF99D3",
          active: "#FF85CA",
        },
        PressureDark: {
          primary: "#FF5CB6",
          background: "#CC0074",
          button: "#FFC2E4",
          hover: "#FF5CB6",
          active: "#FF85C8",
          text: "#CC0074",
          border: "#2D2F33",
        },
        sleep: {
          primary: "#A15BEC",
          background: "#f5dbff",
          hover: "#C499F3",
          active: "#efccfd",
        },
        sleepDark: {
          primary: "#A15BEC",
          background: "#CBA4F4",
          hover: "#C499F3",
          button: "#8124E5",
          active: "#efccfd",
          text: "#FFFFFF",
          border: "#2D2F33",
        },
        bloodGlucose: {
          primary: "#850000",
          background: "#FFD6D6",
          hover: "#a03131",
          active: "#CA3F3F",
          text: "#FF8585",
        },
        bloodGlucoseDark: {
          primary: "#FFD6D6",
          background: "#850000",
          button: "#660000",
          hover: "#FF8585",
          active: "#a03131",
          text: "#FFFFFF",
        },
        weight: {
          primary: "#2E5821",
          background: "#CCFBBE",
          hover: "#B5DB80",
          active: "#BEE090",
        },
        weightDark: {
          primary: "#B5DB80",
          background: "#2E5821",
          button: "#BFE2B6",
          hover: "#B5DB80",
          active: "#BEE090",
          text: "#2E5821",
        },
        // darkBackground: "#141A26",
        darkBackground: "#2A2A27",
      },
    },
  },
  plugins: [],
};
